# Generated by Django 4.0.1 on 2022-01-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='Liked Songs', max_length=50),
        ),
    ]
