# Generated by Django 4.0.1 on 2022-01-31 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_playlist_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='playlists',
            field=models.ManyToManyField(through='songs.PlaylistTrack', to='songs.Playlist'),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='songs.playlist'),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='songs.track'),
        ),
    ]
