# Generated by Django 4.0.1 on 2022-02-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_track_playlists_alter_playlisttrack_playlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='tracks'),
        ),
    ]
