# Generated by Django 4.0.1 on 2022-02-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_alter_track_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='playlists',
        ),
    ]
